Empty repeater field fix
blueliquiddesigns/gravity-forms-pdf-extended pull request #1340
Opened 2022-05-18 05:55 UTC by jestonihpi

## Description
This fixes the issue #1297

## Testing instructions

## Screenshots 

## Checklist:
- [x] I've tested the code.
- [x] My code is easy to read, follow, and understand
- [x] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation / docblocks. 

## Additional Comments

2022-06-06 01:08 UTC, jakejackson1 requested changes
@jestonihpi can we add a unit test to verify this works as expected?

2022-06-06 21:45 UTC, jestonihpi commented
Copy.

2022-06-30 04:11 UTC, jakejackson1 commented
@jestonihpi this works as expected if the Repeater field is not filled out at all. However, Gravity Forms does allow Repeaters to be Nested together and I'd like to see empty Nested Repeater fields removed from the PDF as well.

Here is an example of this occurring in Focus Gravity: [PDF.pdf](https://github.com/GravityPDF/gravity-pdf/files/9016310/PDF.pdf). The top-level repeater is filled out, but the two nested repeaters are not. 

Form used: [gravityforms-export-2022-06-30.json.txt](https://github.com/GravityPDF/gravity-pdf/files/9016309/gravityforms-export-2022-06-30.json.txt) (remove `.txt` extension from file before importing into Gravity Forms).

2022-07-07 00:53 UTC, jestonihpi commented
Added unit test and updated the codebase @jakejackson1 . Thanks.

2022-07-08 03:29 UTC, jakejackson1 commented on src/Helper/Fields/Field_Repeater.php
> +					if ( ! empty( $item[ $sub_field->id ] ) ) {
Would it make more sense to use `! $field->empty_deep( $item[ $sub_field->id ] )` here, to standardise it like the other empty checks?

2022-07-08 03:30 UTC, jakejackson1 commented on src/Helper/Fields/Field_Repeater.php
> +	public function maybe_show_section_title( $is_top_level, $value, $field ) {
This probably doesn't need to be `public`.

2022-07-19 23:58 UTC, merged