Updates on URL arguments
blueliquiddesigns/gravity-forms-pdf-extended pull request #1344
Opened 2022-06-01 23:24 UTC by jestonihpi

## Description
Add an `escape` function for those url that need to be printed as html

## Testing instructions

## Screenshots 

## Checklist:
- [x] I've tested the code.
- [x] My code is easy to read, follow, and understand
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation / docblocks. 

## Additional Comments

2022-06-03 05:09 UTC, jestonihpi commented
Let me know if the PR for the ubuntu fix  is merged @jakejackson1 , so that I can reset this branch and finalize this PR.

2022-06-06 01:04 UTC, jakejackson1 requested changes

2022-06-06 01:04 UTC, jakejackson1 commented on src/Model/Model_Form_Settings.php
> +				'add_new_url' => $add_new_url = esc_url( add_query_arg( [ 'pid' => 0 ] ) ),
@jestonihpi this would be better handled at the point the URL is output in the HTML.

2022-06-06 01:04 UTC, jakejackson1 commented on src/Helper/Helper_PDF_List_Table.php
> +		$edit_url        = esc_url( add_query_arg( [ 'pid' => $item['id'] ] ) );
@jestonihpi this would be better handled at the point the URL is output in the HTML.

2022-06-07 00:50 UTC, jakejackson1 requested changes

2022-06-07 00:50 UTC, jakejackson1 commented on src/View/html/FormSettings/list.php
> +						<a class="button" href="<?= esc_url( esc_url( $args['add_new_url'] ) ) ?>" aria-label="<?= esc_attr__( 'Add new PDF', 'gravity-forms-pdf-extended' ) ?>"><?php esc_html_e( 'Add New', 'gravityfor
@jestonihpi you've wrapped the output in `esc_url()` twice. One of these will need to be removed.

2022-06-07 01:37 UTC, merged