Fix undefined currency number fields on Repeater
blueliquiddesigns/gravity-forms-pdf-extended pull request #1355
Opened 2022-06-24 03:27 UTC by jestonihpi

## Description
Create an array that mimics the entry array structure.

## Testing instructions

## Screenshots 

## Checklist:
- [x] I've tested the code.
- [ ] My code is easy to read, follow, and understand
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation / docblocks. 

## Additional Comments

2022-06-30 04:16 UTC, jakejackson1 requested changes
Missing unit tests

2022-07-07 00:52 UTC, jestonihpi commented
Hi @jakejackson1 , unit test has added. Thanks.

2022-07-19 23:39 UTC, jakejackson1 requested changes
The PR description needs to be updated and have the PR template accurately filled out.

2022-07-19 23:39 UTC, jakejackson1 commented on tests/phpunit/unit-tests/Helper/Fields/Test_Field_Repeater.php
> +		$form  = json_decode( trim( file_get_contents( dirname( __FILE__ ) . '/../../json/repeater-consent-form.json' ) ), true );
Let's handle the importing in the bootstrap file like the other PR.

2022-07-19 23:39 UTC, jakejackson1 commented on tests/phpunit/unit-tests/Helper/Fields/Test_Field_Repeater.php
> +		$items    = $repeater->add_entry_meta( $form_data['repeater'][999][0][15] );
This is a bad unit test. For example, you don't know what the structure of `$form_data['repeater'][999][0][15]` is and you cannot verify the `add_entry_meta()` does what it is meant to do. Further, you aren't testing the value of the array keys to ensure the array replace goes as expected. 

The concern is the `array_replace` overrides the wrong array keys and returns the wrong data, and this is where well-written tests verify the functionality.

Along with passing in different data to `add_entry_meta`, different `$entry` objects should be tested as well.

2022-07-27 23:42 UTC, jakejackson1 requested changes
@jestonihpi almost there.

2022-07-27 23:42 UTC, jakejackson1 commented on src/Helper/Fields/Field_Repeater.php
>  	 * @since 5.1
As this is an entirely new method, the @since tag needs updating.

2022-07-27 23:42 UTC, jakejackson1 commented on tests/phpunit/unit-tests/Helper/Fields/Test_Field_Repeater.php
> +		$this->assertEquals( 1, $items['field_sample_1']);
User `assertSame()` so the type is also checked

2022-07-27 23:42 UTC, jakejackson1 commented on tests/phpunit/unit-tests/Helper/Fields/Test_Field_Repeater.php
> +		$this->assertEquals( 'field_sample_2', key(array_slice($items, -1, 1, true)) );
Running `$items` through `array_values()` and assigning to a new variable, then doing multiple assertions to ensure the order is correctly would be clearer than this one-liner.

2022-07-29 05:02 UTC, jestonihpi commented
Hi @jakejackson1 . Kindly review these changes : https://github.com/GravityPDF/gravity-pdf/pull/1355/commits/2305211414e772e2270721af17cfa5a3508ec746. Thank you.

2022-07-29 05:28 UTC, jakejackson1 approved these changes
@jestonihpi much better with those unit tests. The code looks good to me. Approved.

When I have time I will do a final real-world check on it.

2022-08-02 06:25 UTC, merged