Fix Field Select not displaying when the saved value is 0
blueliquiddesigns/gravity-forms-pdf-extended pull request #1380
Opened 2022-07-19 22:08 UTC by jestonihpi

## Description
Quick update on is_empty method.

#1377

## Testing instructions

## Screenshots 

## Checklist:
- [x] I've tested the code.
- [x] My code is easy to read, follow, and understand
- [x] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation / docblocks. 

## Additional Comments

2022-07-19 23:57 UTC, jakejackson1 requested changes
Needs a unit test and the PR description needs to be updated with appropriate details.

2022-07-28 22:48 UTC, jakejackson1 requested changes
Just need an extra test to verify the change.

2022-07-28 22:48 UTC, jakejackson1 commented on tests/phpunit/unit-tests/Helper/Fields/Test_Field_Select.php
> +	public function test_is_empty_falsey() {
@jestonihpi you should also feed the test a real string like you would expect in a real form entry to verify `is_empty` isn't triggered incorrectly.

2022-07-29 02:47 UTC, jestonihpi commented
Hi @jakejackson1, this PR is now ready for review.

2022-07-29 04:20 UTC, jakejackson1 approved these changes
The code looks good. Approved. 

When I get a chance, I'll run a live test to confirm the functionality and then merge. Nice job.

2022-08-02 06:12 UTC, merged