Move Core Font Installer Notice to selected pages.
blueliquiddesigns/gravity-forms-pdf-extended pull request #1445
Opened 2023-01-13 02:33 UTC by jestonihpi

## Description
WIP. I have only set the  Core Font Installer Notice exclusively to Gravity PDF pages. I need to add this to these pages as well:

1. Form List
2. Form Settings
3. Form Entry List
4. Form Entry Details

#1439 
## Testing instructions

## Screenshots 

## Checklist:
- [ ] I've tested the code.
- [ ] My code is easy to read, follow, and understand
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation / docblocks. 

## Additional Comments

2023-01-13 02:41 UTC, jakejackson1 commented
@jestonihpi I think you've misunderstood. We aren't removing the notice from any existing pages. We are only enabling it on these specific GF pages:


    Form List
    Form Settings
    Form Entry List
    Form Entry Details

2023-01-20 00:53 UTC, jestonihpi commented
Hi @jakejackson1, can you review the recent changes on this PR please?

This would look like on Form list:
![image](https://user-images.githubusercontent.com/434866/213594658-71b86c6f-14ff-4ace-b023-1a2034d098b1.png)
The font will be reset to adapt to the current error messages.

But when its on Gravity PDF pages, it will look like this:
![image](https://user-images.githubusercontent.com/434866/213594797-523d331c-aedb-422a-9304-b01c1531790d.png)

Not sure if this is a good compromise, please advise.

Thanks!

2023-02-22 22:59 UTC, jakejackson1 requested changes
@jestonihpi just a few minor corrections needed.

2023-02-22 22:59 UTC, jakejackson1 commented on src/Controller/Controller_Actions.php
> +						$message = '<br>' . preg_replace( '/(<[^>]+) style=".*?"/i', '$1', $message );
Remove this preg_replace. We can probably always wrap message in a `<p>` or `<div>` tag if the message displays inline with an existing message.

2023-02-22 22:59 UTC, jakejackson1 commented on src/Controller/Controller_Actions.php
> +		if ( ! wp_doing_ajax() && is_admin() && ( $pagenow === 'plugins.php' || $is_gfpdf_page || \GFForms::is_gravity_page() ) ) {
As I mentioned, assign all conditions to individual variables so this IF statement is easy to understad.

2024-07-31 05:41 UTC, jakejackson1 commented
Resolved in https://github.com/GravityPDF/gravity-pdf/pull/1549

2024-07-31 05:41 UTC, closed without merging